insert into marca (marca_id, clave, descripcion) values (seq_marca.nextval, 'MITSUBISHI', 'Es una empresa que fabrica automóviles');
insert into marca (marca_id, clave, descripcion) values (seq_marca.nextval, 'DODGE', 'Es una marca de automóviles y camiones');
insert into marca (marca_id, clave, descripcion) values (seq_marca.nextval, 'AUDI', 'Es una empresa que fabrica automóviles');
insert into marca (marca_id, clave, descripcion) values (seq_marca.nextval, 'CADILLAC', 'Es una empresa que fabrica automóviles');
insert into marca (marca_id, clave, descripcion) values (seq_marca.nextval, 'CHEVROLET', 'Es una empresa multinacional especializada en la industria automotriz');
insert into marca (marca_id, clave, descripcion) values (seq_marca.nextval, 'VOLKSWAGEN', 'Es una empresa multinacional especializada en la industria automotriz');
insert into marca (marca_id, clave, descripcion) values (seq_marca.nextval, 'BMW', 'Es una marca de automóviles y camiones');
insert into marca (marca_id, clave, descripcion) values (seq_marca.nextval, 'MAZDA', 'Es una marca de automóviles y camiones');
insert into marca (marca_id, clave, descripcion) values (seq_marca.nextval, 'MERCEDES-BENZ', 'Es una empresa que fabrica automóviles');
insert into marca (marca_id, clave, descripcion) values (seq_marca.nextval, 'ACURA', 'Es una empresa que fabrica automóviles');
insert into marca (marca_id, clave, descripcion) values (seq_marca.nextval, 'FORD', 'Es una marca de automóviles y camiones');
insert into marca (marca_id, clave, descripcion) values (seq_marca.nextval, 'GMC', 'Es una marca de automóviles y camiones');
