declare
  v_count number;
begin
  select count(*) into v_count
  from marca;
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'S-Class', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Civic', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'S-Type', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, '1000', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Spectra', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Golf', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'X5', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Titan', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Contour', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Familia', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Century', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Accord', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Sierra 3500', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Sportvan G10', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'RX Hybrid', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'RX', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'GT500', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'TL', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Skylark', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'A7', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'PT Cruiser', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Ram 1500', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'S-Class', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Commander', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, '5000CS', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Sunfire', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'S6', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, '3 Series', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Yaris', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Suburban 1500', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, '88', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'XG350', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'S-Type', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'B-Series Plus', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'ES', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Maxima', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'A4', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'RS6', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'SRX', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Express 3500', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Trans Sport', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Rally Wagon 2500', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'xB', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'RL', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Familia', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Yukon XL 2500', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Amanti', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, '626', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Sidekick', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Tiburon', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Accent', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Blazer', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'NSX', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'DeVille', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Venture', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'G-Series 1500', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, '1500 Club Coupe', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Tredia', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'LS', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Prowler', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Celica', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Camaro', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Neon', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Armada', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Sentra', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'E350', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Laser', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Land Cruiser', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'E-Class', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'M6', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, '300ZX', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Boxster', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'G3', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Exige', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'SVX', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Mountaineer', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Ram Van 3500', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Volt', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Sidekick', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Defender', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, '240', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Quattro', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'M3', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Sierra 3500', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Tracer', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Econoline E350', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'IS', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'M3', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Escalade EXT', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'MR2', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Quest', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Colt Vista', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Azera', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, '9-3', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, '5000S', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Equus', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Sequoia', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Express 1500', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Sierra 2500', trunc(dbms_random.value(1, v_count)));
  insert into modelo (modelo_id, nombre, marca_id) values (seq_modelo.nextval, 'Freestyle', trunc(dbms_random.value(1, v_count)));
end;
/